### ISSUE TITLE
USB Camera

### ISSUE THREAD

**Issue by bralafa** [andrewhao/shmile#12]
Is there a way to get this working with a USB camera (computer webcam) on a Raspberry Pi?

**Comment by andrewhao** [comment]
Hey @bralafa - good question. We support any camera that is [officially supported by the gphoto2 library](http://gphoto.sourceforge.net/proj/libgphoto2/support.php). With that said, it doesn't seem like gphoto2 supports that many webcams. Feel free to open an issue at our [official project page](https://github.com/porkbuns/shmile) if you have additional questions.
