### ISSUE TITLE
Processing thumbs/pictures node 0.12.6/npm 2.11.2

### ISSUE THREAD

**Issue by NiklasGER** [andrewhao/shmile#13]
Hello Guys, I am really excited about your photo booth project and installed it the first time I saw it. Unfortunatelly I good some problems with shmile. Is there any place or contact where/whom I can ask my questions? I am total beginner. I am using node v0.12.6 and npm v2.11.2 on my rasbian jessie because I had problem download the right version of node.js with you script. All functions seem to run fine. Webgallery/Initator/Gphoto. But after taking the picture(s) they are not processed and displayed.
Is there any log I can send or post?
Thank you for your support.
BR Niklas

**Comment by andrewhao** [comment]
Hi @NiklasGER - if you visit our new project page at [porkbuns/shmile](https://github.com/porkbuns/shmile), you'll find some folks who have installed on Raspberry Pi (see this page on the wiki: https://github.com/porkbuns/shmile/wiki/Shmile-on-the-Raspberry-Pi). If you have an issue, please create a new issue there. Good luck!
